import PDFDocument from "pdfkit";

export const generateEvaluationReport = (res, summary) => {
  const doc = new PDFDocument({ margin: 40, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=evaluation-report-${summary.procurement.referenceNumber}.pdf`
  );

  doc.pipe(res);

  /* ================= HEADER ================= */
  doc
    .fontSize(16)
    .text("FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA", { align: "center" });

  doc.moveDown(0.5);

  doc
    .fontSize(14)
    .text("PROCUREMENT EVALUATION REPORT", { align: "center" });

  doc.moveDown();

  /* ================= PROCUREMENT INFO ================= */
  doc.fontSize(11);

  doc.text(`Procurement Title: ${summary.procurement.title}`);
  doc.text(`Reference No: ${summary.procurement.referenceNumber}`);
  doc.text(`Department: ${summary.procurement.requestingDepartment}`);
  doc.text(`Opening Date: ${new Date().toDateString()}`);

  doc.moveDown();

  /* ================= TABLE HEADER ================= */

  const startX = 40;
  let y = doc.y;

  doc.font("Helvetica-Bold");

  doc.text("#", startX, y);
  doc.text("Item", startX + 20, y);
  doc.text("Unit", startX + 150, y);

  let offsetX = startX + 200;

  summary.businesses.forEach((b) => {
    doc.text(b.name.substring(0, 10), offsetX, y);
    offsetX += 80;
  });

  doc.text("Winner", offsetX, y);

  doc.moveDown();

  doc.font("Helvetica");

  /* ================= TABLE ROWS ================= */

  summary.items.forEach((item, index) => {
    let rowY = doc.y;

    doc.text(index + 1, startX, rowY);
    doc.text(item.itemName, startX + 20, rowY, { width: 120 });
    doc.text(item.unit, startX + 150, rowY);

    let rowOffsetX = startX + 200;

    summary.businesses.forEach((b) => {
      const price = item.quotes?.[b.businessId]?.unitPrice;
      doc.text(price ? price.toLocaleString() : "-", rowOffsetX, rowY);
      rowOffsetX += 80;
    });

    const winner = summary.businesses.find(
      (b) => b.businessId === item.winnerBusinessId
    )?.name;

    doc.text(winner || "-", rowOffsetX, rowY);

    doc.moveDown();
  });

  doc.moveDown(2);

  /* ================= WINNER SECTION ================= */

  doc.font("Helvetica-Bold").text("Evaluation Result");
  doc.font("Helvetica");

  summary.items.forEach((item) => {
    const winner = summary.businesses.find(
      (b) => b.businessId === item.winnerBusinessId
    )?.name;

    doc.text(`${item.itemName} → Winner: ${winner || "-"}`);
  });

  doc.moveDown(2);

  /* ================= SIGNATURES ================= */

  doc.font("Helvetica-Bold").text("Evaluation Committee");

  doc.moveDown();

  doc.text("Chairperson: __________________________");
  doc.text("Member: _______________________________");
  doc.text("Member: _______________________________");

  doc.moveDown(2);

  doc.text("Approved By: __________________________");

  /* ================= FOOTER ================= */

  doc.moveDown();

  doc.fontSize(9).text("Generated by Procurement Management System", {
    align: "center",
  });

  doc.end();
};